
-- NHS Antidepressant Prescribing Analysis — Forecast Table
--
-- Run AFTER schema.sql has been executed and the
-- nhs_prescribing database already exists.
-- Creates a single forecast table to store the Prophet model output
-- generated by forecast.py. One row per calendar month covering both
-- the historical fitted period and the 12-month forward forecast.
--
-- Power BI connects to this table alongside the existing star schema.
-- The year_month column joins to dates.year_month for the historical
-- period. Future forecast months will not exist in dates — this is
-- intentional and no foreign key is enforced for this reason.

USE nhs_prescribing;

-- forecast
-- One row per calendar month.
-- Historical rows (is_forecast=0): actual values populated, forecast values
--   represent the Prophet fitted values for that month.
-- Forecast rows (is_forecast=1): actual values are NULL, forecast values
--   represent the Prophet 12-month forward projection.
--
-- Example historical row:
--   year_month='2021-01', actual_items=6500000, actual_nic=25200000.00,
--   actual_cpi=3.88, items_forecast=6480000.00, is_forecast=0
--
-- Example forecast row:
--   year_month='2025-05', actual_items=NULL, actual_nic=NULL,
--   actual_cpi=NULL, items_forecast=7620000.00, is_forecast=1

CREATE TABLE IF NOT EXISTS forecast (
    forecast_id    INT             NOT NULL AUTO_INCREMENT,
    `year_month`   VARCHAR(7)      NOT NULL,               -- e.g. '2021-01'

    -- Actual observed national totals (NULL for future forecast months)
    actual_items   BIGINT                   DEFAULT NULL,  -- total items prescribed nationally
    actual_nic     DECIMAL(15, 2)           DEFAULT NULL,  -- total NIC in GBP
    actual_cpi     DECIMAL(10, 4)           DEFAULT NULL,  -- mean cost per item in GBP

    -- Items forecast with 80% confidence interval
    items_forecast DECIMAL(15, 2)  NOT NULL,
    items_lower    DECIMAL(15, 2)  NOT NULL,
    items_upper    DECIMAL(15, 2)  NOT NULL,

    -- NIC (cost) forecast with 80% confidence interval
    nic_forecast   DECIMAL(15, 2)  NOT NULL,
    nic_lower      DECIMAL(15, 2)  NOT NULL,
    nic_upper      DECIMAL(15, 2)  NOT NULL,

    -- Cost per item forecast with 80% confidence interval
    cpi_forecast   DECIMAL(10, 4)  NOT NULL,
    cpi_lower      DECIMAL(10, 4)  NOT NULL,
    cpi_upper      DECIMAL(10, 4)  NOT NULL,

    -- 1 = future forecast month, 0 = historical fitted month
    is_forecast    TINYINT(1)      NOT NULL DEFAULT 0,

    PRIMARY KEY (forecast_id),
    UNIQUE KEY uq_forecast_year_month (`year_month`),
    INDEX idx_forecast_is_forecast (is_forecast)
)
ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COMMENT = 'Prophet 12-month forecast for national antidepressant items, NIC and cost per item. Generated by forecast.py.';

SHOW TABLES;